# Generated by Django 5.2.4 on 2025-10-06 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NameCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Категория имён',
                'verbose_name_plural': 'Категории имён',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AvarName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя на аварском')),
                ('translation', models.CharField(help_text='Значение имени или эквивалент на русском/английском', max_length=256, verbose_name='Перевод')),
                ('translit', models.CharField(blank=True, max_length=128, verbose_name='Транслитерация')),
                ('gender', models.CharField(choices=[('male', 'Мужское'), ('female', 'Женское'), ('unisex', 'Универсальное')], default='unisex', max_length=10, verbose_name='Пол')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='names.namecategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Аварское имя',
                'verbose_name_plural': 'Аварские имена',
                'ordering': ['category', 'name'],
                'unique_together': {('category', 'name', 'gender')},
            },
        ),
    ]
